[package]
name = "ettac"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.14"
mlua = { version = "0.11.6", features = ["lua54", "async", "vendored", "serde"]}
russh = "0.57.0"

serde = "1.0"
serde_json = "1.0"
